services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"   # http://localhost:3000 -> Vite (5173 dans le container)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - beautyconnect_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"   # http://localhost:5000 -> Express API
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/beautyconnect
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - beautyconnect_net

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - beautyconnect_net

volumes:
  mongo_data:

networks:
  beautyconnect_net:
